"" General
set nocompatible

set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'

"" Interface
Bundle 'kien/ctrlp.vim'
Bundle 'vim-scripts/ZoomWin'
Bundle 'The-NERD-tree'
Bundle 'Lokaltog/vim-powerline'
Bundle 'benmills/vimux'
Bundle 'tpope/vim-dispatch'
Bundle 'skalnik/vim-vroom'

"" Search
Bundle 'rking/ag.vim'

"" Code edit
Bundle 'The-NERD-Commenter'
Bundle 'tpope/vim-unimpaired'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-endwise'
Bundle 'godlygeek/tabular'
Bundle 'ervandew/vim-supertab'
Bundle 'majutsushi/tagbar'
Bundle 'terryma/vim-multiple-cursors'

"" Ruby & Rails stuff
Bundle 'vim-ruby/vim-ruby'
Bundle 'pgr0ss/vimux-ruby-test'
Bundle 'ecomba/vim-ruby-refactoring'
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-bundler'
Bundle 'tpope/vim-rake'

"" Code snippets
Bundle 'tomtom/tlib_vim'
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'garbas/vim-snipmate'
Bundle 'honza/vim-snippets'
Bundle 'aperezdc/vim-template'

"" Markdown
Bundle 'tpope/vim-markdown'
Bundle 'waylan/vim-markdown-extra-preview'

"" Git & Github
Bundle 'tpope/vim-fugitive'
Bundle 'mattn/webapi-vim'
Bundle 'mattn/gist-vim'

"" Coffee, slim, etc.
Bundle 'kchmck/vim-coffee-script'
Bundle 'slim-template/vim-slim'

"" Colorschemes
Bundle 'altercation/vim-colors-solarized'
Bundle 'chriskempson/tomorrow-theme'
Bundle 'w0ng/vim-hybrid'

syntax on
filetype plugin indent on	  " Load file type plugins + indentation
set fileencoding=utf-8    	" set encoding
set linebreak
set history=1000
set mouse=a
set ttyfast
set hidden
set autoread
set showcmd			            " display incomplete commands
let mapleader=","		        " use comma as <Leader> key instead of backslash

"" Visual clues
set ruler
set cursorline
set showbreak=↪
:au FocusLost * :set number
:au FocusGained * :set relativenumber
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

"" Colours
"let g:hybrid_use_Xresources = 1
"silent! colorscheme hybrid
let &t_Co=256
silent! colorscheme Tomorrow-Night-Eighties
set background=dark

"" Undo across sessions
if has('gui_running')
   set undodir=~/.vim/backups
   set undofile
endif

"" Whitespace
set nowrap			                    " don't wrap lines
set tabstop=2 shiftwidth=2	        " a tab is two spaces
set softtabstop=2
set expandtab			                  " use spaces, not tabs
set list listchars=tab:\ \ ,trail:·	" set trailing space name
set backspace=indent,eol,start	    " backspace through everything in insert mode

"" Searching
set hlsearch			          " highlight matches
set incsearch			          " incremental searching
set ignorecase			        " searches are case insensitive
set smartcase			          " ..unless they contatin at least one capital letter
nnoremap <F3> :set hlsearch!<CR>	" switch highlighting

"" Scrolling
set scrolloff=10
set sidescrolloff=15
set sidescroll=1

"" Backups
set nobackup
set nowritebackup
set noswapfile

"" Navigation
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l

"" Get off my lawn
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Down> :echoe "Use j"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Right> :echoe "Use l"<CR>

"" Backup
set backupdir=~/.vim/backup
set directory=~/.vim/backup

"" Zoomwin
map <Leader>= <C-w>=
map <Leader><Leader> :ZoomWin<CR>

"" Ag
map <Leader>f :Ag<space>

"" NERDTree config
map <Leader>n :NERDTreeToggle<CR>
map <Leader>m :NERDTreeFind<CR>

"" Ctrlp
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'

"" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.pyc,*.zip,*.gz,*.bz,*.tar,*.jpg,*.png,*.png,*.gif,*.avi,*.wmv,*.ogg,*.mp3,*.mov,*.so,*.swp,*.zip

"" Filetypes
au BufNewFile,BufRead {Capfile,Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru,*.rabl,*.rake}  set syntax=ruby
au BufNewFile,BufRead *.json                set syntax=javascript
au BufNewFile,BufRead *.md,*.mkd,*.markdown set syntax=markdown

let g:VMEPstylesheet = 'github2.css'

"" SnipMate
let g:snipMate = {}
let g:snipMate.scope_aliases = {}
let g:snipMate.scope_aliases['ruby'] = 'ruby,ruby-rails,ruby-1.9'

"" Trailing whitespace remove on save
autocmd BufWritePre *.rb,*.py,*.c,*.h,*.feature,*.conf,*rc,README,CHANGELOG,README.* :%s/\s\+$//e

"" Toggle pasting
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

"" Bubble signle lines
nmap <C-Up> [e
nmap <C-Down> ]e

"" Bubble multiple lines
vmap <C-Up> [egv
vmap <C-Down> ]egv

"" Tabular
if exists(":Tabularize")
  nmap <Leader>a= :Tabularize /=<CR>
  vmap <Leader>a= :Tabularize /=<CR>
  nmap <Leader>a> :Tabularize /=><CR>
  vmap <Leader>a> :Tabularize /=><CR>
  nmap <Leader>a: :Tabularize /:\zs<CR>
  vmap <Leader>a: :Tabularize /:\zs<CR>
endif

"" Gist
let g:gist_clip_command = 'pbcopy'
let g:gist_detect_filetype = 1
let g:gist_show_privates = 1

"" Powerline
let g:Powerline_symbols = 'fancy'
set laststatus=2

"" Tagbar
nmap <Leader>tb :TagbarToggle<CR>

"" Vim templates
let g:templates_no_autocmd = 1

"" XML prettify
function! PrettifyXML()
  set ft=xml
  :%s/></>\r</g
  :0
  :norm =G
endfunction
